sudo: false

language: generic

branches:
  only:
    - master

addons:
  apt:
    packages:
      - g++-8
      - cmake
      - doxygen
      - libopenal-dev
      - libjpeg-dev
      - libudev-dev
      - libxrandr-dev
      - libfreetype6-dev
      - libvorbis-dev
      - libflac-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
    sources: &sources
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test

compiler: g++-8
os: linux

install:
  - scripts/sfml.sh

env:
  - COMMAND="scripts/build.sh" COMPILER_NAME=gcc CXX=g++-8 CC=gcc-8 ENV=tests
  - COMMAND="doxygen Doxyfile" COMPILER_NAME=gcc CXX=g++-8 CC=gcc-8 ENV=doc

script:
  - (eval "$COMMAND")

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition: $ENV = doc
